DROP TABLE IF EXISTS VOTOS;
DROP TABLE IF EXISTS SESSOES;
DROP TABLE IF EXISTS ASSOCIADOS;
DROP TABLE IF EXISTS PAUTAS;

CREATE TABLE IF NOT EXISTS PAUTAS (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS ASSOCIADOS (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSOES (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PAUTA INT UNSIGNED NOT NULL,
    ABERTURA TIMESTAMP NOT NULL,
    FECHAMENTO TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_PAUTA) REFERENCES PAUTAS(ID)
);

CREATE TABLE IF NOT EXISTS VOTOS (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_SESSAO INT UNSIGNED NOT NULL,
    ID_ASSOCIADO INT UNSIGNED NOT NULL,
    VOTO BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSOES(ID),
    FOREIGN KEY (ID_ASSOCIADO) REFERENCES ASSOCIADOS(ID)
);
